feat: CLOUD-1992 Improved nightly pipeline notifications
Added notifications for pipeline failures and random passwords generated for nightly environment lskdjf lkdfj

Squashed commit of the following:

commit e5e5a767f0d46aab21cc75dbd3a36e45bc7d02c2
Merge: 67b8f3e6a 330adf1c0
Author: jcastillo <jcastillo@localhost>
Date:   Mon Mar 16 15:07:20 2020 -0700

    Merge branch 'master' into CLOUD-1992

commit 67b8f3e6a4512278de0ad80249ce5034e518127f
Author: jcastillo <jcastillo@localhost>
Date:   Mon Mar 16 10:45:17 2020 -0700

    CLOUD-1992 Fix Bug with notifications' text

commit 4d03539217c774a1aa1bab474420581e74794106
Author: jcastillo <jcastillo@localhost>
Date:   Fri Mar 13 15:57:00 2020 -0700

    CLOUD-1992 Added failure notification to nightly pipeline

commit 2619a524f39392a4f2dbc6e0236c0af3ddca2bbc
Author: jcastillo <jcastillo@localhost>
Date:   Wed Mar 11 15:55:50 2020 -0700

    CLOUD-1992 Enable password notification for nightly env

diff --git a/cicd/tekton/create-users-task.yaml b/cicd/tekton/create-users-task.yaml
--- a/cicd/tekton/create-users-task.yaml
+++ b/cicd/tekton/create-users-task.yaml
@@ -9,20 +9,43 @@ spec:
       - name: users
         type: string
         description: number of users to create
+  stepTemplate:
+    env:
+    - name: SLACK_FAILED_WEBHOOK_URL
+      valueFrom:
+        secretKeyRef:
+          name: slack-webhook
+          key: SLACK_FAILED_WEBHOOK_URL
   steps:
     - name: wait-for-all-pods-ready
       image: gcr.io/cloud-builders/kubectl
-      command: ["bash", "-c"]
-      args: ["sleep 15; kubectl wait --for=condition=ready --timeout=600s pod -l vendor=forgerock --all"]
+      script: |
+        #!/usr/bin/env bash
+        {
+          sleep 15
+          kubectl wait --for=condition=ready --timeout=600s pod -l vendor=forgerock --all
+        } || {
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Some pods still unhealthy after 600s. Failed to create users"}' $SLACK_FAILED_WEBHOOK_URL
+        }
 
     - name: wait-for-amster-config
       image: gcr.io/cloud-builders/kubectl
-      command: ["bash", "-c"]
-      # Obtain the amster pod name, tail the logs until the string is found
-      args: ['(kubectl logs $(kubectl get pod -l app=amster -o jsonpath="{.items[0].metadata.name}") -f &) | grep -qi "configuration script finished"']
+      script: |
+        #!/usr/bin/env bash
+        {
+          # Obtain the amster pod name, tail the logs until the string is found      
+          (kubectl logs $(kubectl get pod -l app=amster -o jsonpath="{.items[0].metadata.name}") -f &) | grep -qi "configuration script finished"
+        } || {
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Amster config failed"}' $SLACK_FAILED_WEBHOOK_URL
+        }
       
     - name: create-users
       image: gcr.io/cloud-builders/kubectl
-      command: ["bash", "-c"]
-      args: ["kubectl exec ds-idrepo-0 make-users.sh $(inputs.params.users)"]
+      script: |
+        #!/usr/bin/env bash
+        {
+          kubectl exec ds-idrepo-0 make-users.sh $(inputs.params.users)
+        } || {
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed to create users. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
+        }      
     
diff --git a/cicd/tekton/deploy-images-task.yaml b/cicd/tekton/deploy-images-task.yaml
--- a/cicd/tekton/deploy-images-task.yaml
+++ b/cicd/tekton/deploy-images-task.yaml
@@ -7,17 +7,28 @@ spec:
     resources:
     - name: forgeops
       type: git
+  stepTemplate:
+    env:
+    - name: SLACK_FAILED_WEBHOOK_URL
+      valueFrom:
+        secretKeyRef:
+          name: slack-webhook
+          key: SLACK_FAILED_WEBHOOK_URL
   steps:
   # Executes skaffold with the kaniko builder to build in cluster
   - name: delete-current-env
     image: "gcr.io/k8s-skaffold/skaffold-in-cluster-builder:latest"
     script: |
       #!/usr/bin/env bash
-      #HACK NEED BETTER IMAGE WITH KUSTOMIZE INCLUDED. KUSTOMIZE == 11MB DOWNLOAD
-      curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
-      cp kustomize /usr/local/bin
-      cd /workspace/forgeops
-      skaffold -f skaffold.yaml -p nightly delete
+      {
+        #HACK NEED BETTER IMAGE WITH KUSTOMIZE INCLUDED. KUSTOMIZE == 11MB DOWNLOAD
+        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
+        cp kustomize /usr/local/bin
+        cd /workspace/forgeops
+        skaffold -f skaffold.yaml -p nightly delete
+      } || { #If something fails
+        curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed to delete old environment. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
+      }
 
   - name: delete-pvcs
     image: gcr.io/cloud-builders/kubectl
@@ -28,14 +39,17 @@ spec:
     image: "gcr.io/k8s-skaffold/skaffold-in-cluster-builder:latest"
     script: |
       #!/usr/bin/env bash
-      #HACK NEED BETTER IMAGE WITH KUSTOMIZE INCLUDED. KUSTOMIZE == 11MB DOWNLOAD
-      curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
-      cp kustomize /usr/local/bin
-      cd /workspace/forgeops
-      cd bin
-      ./config.sh init -v 7.0 -p cdk
-      cd ..
-      sleep 30
-      skaffold -f skaffold.yaml -p nightly --default-repo=gcr.io/engineering-devops/nightly render >render.yaml
-      kubectl apply -f render.yaml
-
+      {
+        #HACK NEED BETTER IMAGE WITH KUSTOMIZE INCLUDED. KUSTOMIZE == 11MB DOWNLOAD
+        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
+        cp kustomize /usr/local/bin
+        cd /workspace/forgeops
+        cd bin
+        ./config.sh init -v 7.0 -p cdk
+        cd ..
+        sleep 30
+        skaffold -f skaffold.yaml -p nightly --default-repo=gcr.io/engineering-devops/nightly --status-check=false run
+      } || {
+        curl -X POST -H 'Content-type: application/json' --data '{"text":"Skaffold failed to deploy new environment. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
+      }
+      
diff --git a/cicd/tekton/scale-am-deployment-task.yaml b/cicd/tekton/scale-am-deployment-task.yaml
--- a/cicd/tekton/scale-am-deployment-task.yaml
+++ b/cicd/tekton/scale-am-deployment-task.yaml
@@ -9,11 +9,23 @@ spec:
       - name: replicas
         type: string
         description: number of users to create
+  stepTemplate:
+    env:
+    - name: SLACK_FAILED_WEBHOOK_URL
+      valueFrom:
+        secretKeyRef:
+          name: slack-webhook
+          key: SLACK_FAILED_WEBHOOK_URL
   steps:
     - name: scale-am-tozero
       image: gcr.io/cloud-builders/kubectl
-      command: ["bash", "-c"]
-      args: ["kubectl scale deployment am --replicas=0"]
+      script: |
+        #!/usr/bin/env bash
+        {
+          kubectl scale deployment am --replicas=0
+        } || {
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed to scale AM to zero. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
+        }
 
     - name: wait-10-seconds
       image: gcr.io/cloud-builders/kubectl
@@ -22,11 +34,22 @@ spec:
       
     - name: scale-am-todesired
       image: gcr.io/cloud-builders/kubectl
-      command: ["bash", "-c"]
-      args: ["kubectl scale deployment am --replicas=$(inputs.params.replicas)"]
+      script: |
+        #!/usr/bin/env bash
+        {
+          kubectl scale deployment am --replicas=$(inputs.params.replicas)
+        } || {
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed to scale AM back to $(inputs.params.replicas). See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
+        }
 
     - name: wait-for-all-pods-ready
       image: gcr.io/cloud-builders/kubectl
-      command: ["bash", "-c"]
-      args: ["sleep 15; kubectl wait --for=condition=ready --timeout=600s pod -l vendor=forgerock --all"]
+      script: |
+        #!/usr/bin/env bash
+        {
+          sleep 15
+          kubectl wait --for=condition=ready --timeout=600s pod -l vendor=forgerock --all
+        } || {
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Some pods are not healthy after AM restart. See pipeline logs"}' $SLACK_FAILED_WEBHOOK_URL
+        }
     
