feat: New `bin/forgeops` command
1. New `bin/forgeops` command
1. `bin/forgeops` will replace `bin/cdm` and `bin/cdk`
1. Deprecate `bin/cdk`
1. Update `bin/cdk` references to `bin/forgeops`
1. Remove `bin/cdm`

ref: CLOUD-3339

diff --git a/bin/cdk b/bin/cdk
--- a/bin/cdk
+++ b/bin/cdk
@@ -1,168 +1,32 @@
-#!/usr/bin/env python3
-"""This script deploys the ForgeRock Identity Platform to Kubernetes."""
+#!/usr/bin/env bash
+echo $'\e[5;31m'
+echo "**********************************************************************************"
+echo "***********THIS SCRIPT IS DEPRECATED. USE /bin/forgeops INSTEAD*******************"
+echo "**********************************************************************************"
+echo $'\e[0m'
+read -r -d '' DEP <<'EOF'
+=====================
+Notice of Deprecation
+=====================
 
-import argparse
-import os
-import sys
-import time
-import utils
-import json
+# What's Changed:
 
-build_targets = ['am', 'amster', 'idm', 'ds-idrepo', 'ds-cts', 'ig']
+  The script `bin/cdk` is being replaced by `bin/forgeops`. This new script will manage both CDK and CDM deployments.
 
-def install_all(size, ns, fqdn, ctx):
-    """Deploy all components in sequence"""
-    pkg_path = os.path.join(sys.path[0], '..', 'kustomize', 'cdk')
-    utils.message('Deploying base.yaml. This is a one time activity.')
-    utils.install_component('base', size, ns, fqdn, ctx, pkg_path)
-    utils.install_component('secrets', size, ns, fqdn, ctx, pkg_path)
-    utils.message('\nDeploying ds.yaml. This is includes all directory resources.')
-    utils.install_component('ds', size, ns, fqdn, ctx, pkg_path)
-    utils.message('\nWaiting for DS deployment. This can take a few mins. First installation takes longer.')
-    time.sleep(2)
-    utils.wait_for_ds(ns, 'ds-idrepo')
-    if size not in ['cdk', 'mini']: utils.wait_for_ds(ns, 'ds-cts')
-    utils.message('\nDeploying apps.')
-    utils.install_component('apps', size, ns, fqdn, ctx, pkg_path)
-    utils.message('\nWaiting for AM deployment. This can take a few minutes. First installation takes longer.')
-    time.sleep(2)
-    utils.run('kubectl', f'-n {ns} wait --for=condition=Available deployment -l app.kubernetes.io/name=am --timeout=600s')
-    utils.message('\nWaiting for amster job to complete. This can take several minutes.')
-    utils.run('kubectl', f'-n {ns} wait --for=condition=complete job/amster --timeout=600s')
-    utils.message('\nRemoving "amster" deployment.')
-    utils.uninstall_component('amster', ns, False)
-    utils.message('\nWaiting for IDM deployment. This can take a few minutes. First installation takes longer.')
-    utils.run('kubectl', f'-n {ns} wait --for=condition=Ready pod -l app=idm --timeout=600s')
-    utils.message('\nDeploying UI.')
-    utils.install_component('ui', size, ns, fqdn, ctx, pkg_path)
-    # message('\nWaiting for UI pods to become ready')
-    # run('kubectl', f'-n {ns} wait --for=condition=Available deployment -l app.kubernetes.io/component=ui --timeout=600s')
+# How does this impact me?
 
-def overlay_app_configs(ns, am=True, idm=True):
-    """Overlay local configs in the AM and IDM pods"""
-    config_profile_path = os.path.join(sys.path[0], '../docker')
-    if am:
-        am_config_path = os.path.join(config_profile_path, 'am', 'config-profiles', 'cdk', 'config')
-        _, am_pod_name, _ = utils.run('kubectl', f'-n {ns} get pods -l app.kubernetes.io/name=am -o jsonpath={{.items[0].metadata.name}}',
-                                      cstdout=True)
-        am_pod_name = am_pod_name.decode('ascii')
-        utils.message(f'Copying your local AM configs into "{am_pod_name}" pod in "{ns}" namespace')
-        utils.run('kubectl', f'-n {ns} cp {am_config_path} {am_pod_name}:/home/forgerock/openam/ -c openam')
-    if idm:
-        _, idm_pod_name, _ = utils.run('kubectl', f'-n {ns} get pods -l app.kubernetes.io/name=idm -o jsonpath={{.items[0].metadata.name}}',
-                                       cstdout=True)
-        idm_pod_name = idm_pod_name.decode('ascii')
-        utils.message(f'Copying your local IDM configs into "{idm_pod_name}" pod in "{ns}" namespace')
-        for directory in os.listdir(os.path.join(config_profile_path, 'idm', 'config-profiles', 'cdk')):
-            idm_config_path = os.path.join(config_profile_path, 'idm', 'config-profiles', 'cdk', directory)
-            utils.run('kubectl', f'-n {ns} cp {idm_config_path} {idm_pod_name}:/opt/openidm/ -c openidm')
+  * The script `bin/cdk` is deprecated and will be removed in a future release. 
+  * You should promptly apply necessary updates to any scripts using `bin/cdk`.
+  * Start using `bin/forgeops` to install and delete CDK deployments.
 
-    utils.message('Restarting AM and IDM pods')
-    if am:
-        utils.run('kubectl', f'-n {ns} exec {am_pod_name}  -c openam  -- kill 1')
-    if idm:
-        utils.run('kubectl', f'-n {ns} exec {idm_pod_name} -c openidm -- kill 1')
+# What should I use to deploy the ForgeRock CDK?
 
-def build_docker_image(component, default_repo, tag, config_profile=None):
-    """Builds custom docker images"""
-    kustomize_dir = os.path.join(sys.path[0], '..', 'kustomize')
-    image_defaulter = os.path.join(kustomize_dir, 'dev', 'image-defaulter')
-    tag_data = utils.build_docker_image(component, default_repo, tag, config_profile)
-    name = utils.DOCKER_REGEX_NAME.get(component, component)
-    utils.run('kustomize', f'edit set image {name}={tag_data}', cwd=image_defaulter)
-    utils.warning(f'Updated the image_defaulter with your new image for {component}: "{tag_data}"')
+  Please use `bin/forgeops install --cdk` instead. Command arguments used by `bin/cdk`
+  continue to be supported in `bin/forgeops`.
+  By default, `bin/forgeops install` and `bin/forgeops generate` will target CDK deployments.
 
-def main():
+EOF
+printf "%-10s \n" "$DEP" >&2
 
-    common = argparse.ArgumentParser(add_help=False)
-    common.add_argument('-n', '--namespace', default='',
-                        help='Target namespace (default: current namespace)')
-    common.add_argument('components', nargs='*', choices=['all', 'base', 'ds', 'apps', 'ui', 'am', 'amster', 'idm',
-                                                          'ds-idrepo', 'ds-cts', 'admin-ui', 'end-user-ui', 'login-ui', 'ig',
-                                                          'rcs-agent', []])
-    parser = argparse.ArgumentParser(
-        description='Manage ForgeRock platform components')
-    subparser = parser.add_subparsers(dest='cmd', required=True)
-    parser_install = subparser.add_parser('install', parents=[common],
-                                          help='Install the platform components or component bundles using local manifests')
-    parser_install.add_argument('-f', '--fqdn', dest='fqdn',
-                                help='Select the FQDN for this deployment')
-    parser_delete = subparser.add_parser(
-        'delete', parents=[common], help='Delete ForgeRock Platform components or component bundles')
-    parser_delete.add_argument('-y', '--yes', dest='skip_confirmation', action='store_true',
-                               help='Skip delete confirmation')
-    parser_build = subparser.add_parser('build', help='Build custom docker images')
-    parser_build.add_argument('components', nargs='*', choices=['all'] + build_targets, default= 'all')
-    parser_build.add_argument('-r', '--default-repo', dest='registry')
-    parser_build.add_argument('-t', '--tag', required=False)
-    parser_build.add_argument('-p', '--config-profile', dest='config_profile')
-    parser_build.add_argument('--reset', action='store_true', help='Reset the image-defaulter file')
-    parser_info = subparser.add_parser('info', parents=[common], help='Print relevant deployment information')
-    parser_info.add_argument('--json', dest='jsonfmt', action='store_true', help='Print information in JSON format')
-    subparser.add_parser('config', parents=[common]) # Internal use. Hidden
-    args = parser.parse_args()
-
-    # Check toolset versions before doing anything
-    utils.check_base_toolset()
-    if args.cmd != 'build':
-        ctx_namespace = utils.get_namespace()
-        ctx = utils.get_context()
-        namespace = getattr(args, 'namespace', None) or ctx_namespace
-        fqdn = args.fqdn if getattr(args, 'fqdn', None) else f'{namespace}.iam.example.com'
-
-    components = args.components if getattr(args, 'components', None) else ['all']
-    if args.cmd == 'info':
-        if not args.jsonfmt:
-            utils.message(f'Targeting namespace: "{namespace}"')
-        secrets = utils.printsecrets(namespace, not args.jsonfmt)
-        urls = utils.printurls(namespace, not args.jsonfmt)
-        output = {'context': ctx, 'namespace': namespace, 'secrets': secrets, 'urls': urls}
-        if args.jsonfmt:
-            print(json.dumps(output))
-        return
-    if args.cmd == 'config':
-        overlay_app_configs(namespace)
-        return
-    if args.cmd is None:
-        parser.print_help()
-        sys.exit(1)
-    if args.cmd == 'delete':
-        utils.message(f'Uninstalling component(s): {components} from namespace: "{namespace}"')
-        if not args.skip_confirmation:
-            if input('OK to delete these components? [Y/N] ').lower() not in ['yes', 'y']:
-                return
-        if 'base' in components: #delete 'base' last
-            components.append(components.pop(components.index('base')))
-        for c in components:
-            utils.uninstall_component(c, namespace, True)
-        return
-    if args.cmd == 'build':
-        if args.reset:
-            image_defaulter = os.path.join(sys.path[0], '../kustomize', 'dev', 'image-defaulter' )
-            utils.message(f'Reset to git index: {image_defaulter} ')
-            utils.run('git', f'checkout {image_defaulter}')
-            return
-        if 'all' in components:
-            components = build_targets
-        if 'amster' in components:
-            utils. error('Embedding AM dynamic configs in the amster image is deprecated. Manage AM dynamic config with the bin/amster cmd instead.')
-        for c in components:
-            build_docker_image(c, args.registry, args.tag, args.config_profile)
-        return
-    utils.install_dependencies()
-    utils.message(f'Installing component(s): {components} in namespace: "{namespace}"\n')
-    if 'all' in components:
-        install_all('cdk', namespace, fqdn, ctx)
-    else:
-        for c in components:
-            pkg_path = os.path.join(sys.path[0], '..', 'kustomize', 'cdk')
-            utils.install_component(c, 'cdk', namespace, fqdn, ctx, pkg_path)
-
-    if args.cmd == 'install' and ('base' in components or 'all' in components):
-        utils.waitforsecrets(namespace)
-        utils.printsecrets(namespace)
-        utils.printurls(namespace)
-    utils.message('\nEnjoy your deployment!')
-
-if __name__ == '__main__':
-    main()
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || die "Couldn't determine the script's running directory" 2
+exec $SCRIPT_DIR/forgeops "$@"
