fix: Replace $REPO with $HOST
$REPO contains no value so replaced with $HOST.
Disable ds-set-passwords from secret-generator folder as Kustomize was trying to deploy it twice.
Fix broken SEARCH_RESPONSE variable.

ref: FORGEOPS-6007

diff --git a/kustomize/base/ds/set-passwords/resources.yaml b/kustomize/base/ds/set-passwords/resources.yaml
--- a/kustomize/base/ds/set-passwords/resources.yaml
+++ b/kustomize/base/ds/set-passwords/resources.yaml
@@ -90,7 +90,7 @@ data:
     echo 'Password script finished'
 
     echo "done"
-  start.sh: "#!/usr/bin/env bash\n\n# Checking PingDS is up\n\nwait_repo() {\n    local HOST=\"$1-0.$1\"\n    local USER_DN=$2\n    local USER_UID=$3\n    local CXN=\"-h ${HOST} -p 1636 --useSsl --trustAll\"\n    echo \"Waiting for $HOST to be available.\"\n    SEARCH_CMD=\"ldapsearch ${CXN} -D 'uid=admin' -w '${ADMIN_PASS}' -b ${USER_DN} '${USER_UID}'\"\n    eval $SEARCH_CMD\n    SEARCH_REPONSE=$?\n    while [[ \"$SEARCH_RESPONSE\" != \"0\" ]] ; do\n        sleep 5;\n        eval $SEARCH_CMD\n        SEARCH_RESPONSE=$?\n    done\n    echo \"$REPO is responding\"\n}\n\nADMIN_PASS=$(cat /var/run/secrets/opendj-passwords/dirmanager.pw)\n\nwait_repo ds-idrepo ou=admins,ou=identities \"uid=am-identity-bind-account\" \nwait_repo ds-cts ou=admins,ou=famrecords,ou=openam-session,ou=tokens \"uid=openam_cts\" \n\n# Set the PingDS passwords for each store\nif [ -f \"/opt/opendj/ds-passwords.sh\" ]; then\n    echo \"Setting directory service account passwords\"\n    /opt/opendj/ds-passwords.sh\n    if [ $? -ne 0 ]; then\n        echo \"ERROR: Pre install script failed\"\n        exit 1\n    fi\nfi\n"
+  start.sh: "#!/usr/bin/env bash\n\n# Checking PingDS is up\n\nwait_repo() {\n    local HOST=\"$1-0.$1\"\n    local USER_DN=$2\n    local USER_UID=$3\n    local CXN=\"-h ${HOST} -p 1636 --useSsl --trustAll\"\n    echo \"Waiting for $HOST to be available.\"\n    SEARCH_CMD=\"ldapsearch ${CXN} -D 'uid=admin' -w '${ADMIN_PASS}' -b ${USER_DN} '${USER_UID}'\"\n    eval $SEARCH_CMD\n    SEARCH_RESPONSE=$?\n    while [[ \"$SEARCH_RESPONSE\" != \"0\" ]] ; do\n        sleep 5;\n        eval $SEARCH_CMD\n        SEARCH_RESPONSE=$?\n    done\n    echo \"$HOST is responding\"\n}\n\nADMIN_PASS=$(cat /var/run/secrets/opendj-passwords/dirmanager.pw)\n\nwait_repo ds-idrepo ou=admins,ou=identities \"uid=am-identity-bind-account\" \nwait_repo ds-cts ou=admins,ou=famrecords,ou=openam-session,ou=tokens \"uid=openam_cts\" \n\n# Set the PingDS passwords for each store\nif [ -f \"/opt/opendj/ds-passwords.sh\" ]; then\n    echo \"Setting directory service account passwords\"\n    /opt/opendj/ds-passwords.sh\n    if [ $? -ne 0 ]; then\n        echo \"ERROR: Pre install script failed\"\n        exit 1\n    fi\nfi\n"
 ---
 # Source: identity-platform/templates/ds-set-passwords-job.yaml
 apiVersion: batch/v1
