feat: Base images are based on nightly forgeops image builds
Moving the builds back over to forgeops-public. This is required because we need a secret to pull platform images repo which lives in forgeops-public and will leave builds isolated from engineering-devops.
I had to drop the usage of "./bin/cdk build" because it requires access
to a cluster in order to run build. There is no cluster in that project.

Additional drops rcs-agent and ui images from image-defaulter and
removes hard coded images in deployment objects in favor of
kustomization.yaml setting this.

ref: CLOUD-3241

diff --git a/cicd/bin/build-image-tags b/cicd/bin/build-image-tags
--- a/cicd/bin/build-image-tags
+++ b/cicd/bin/build-image-tags
@@ -40,13 +40,13 @@ EOF
     && { . ${SCRIPT_DIR}/lib-git-auth.sh \
         || { echo "failed to configure credentials" && exit 1; };}
 
-
-if ! ${REPO_DIR}/bin/platform-config --profile-name "${PROFILE_NAME}";
+# Use platform-images but the latest postcommit
+if ! ${REPO_DIR}/bin/set-images;
 then
-    echo "failed to build config"
-    exit 1
+    echo "failed to set base images for build"
 fi
 
+export CONFIG_PROFILE=${PROFILE}
 if ! (cd ${REPO_DIR}; skaffold --filename skaffold.yaml \
                                --profile docker-image-tag \
                                --default-repo "${REPO}" \
